version: '3'
services:
  smtp:
    image: namshi/smtp
    env_file:
     - .env
    logging:
      driver: none # SMTP docker image is very verbose, prevent all logging

  server:
    build: .
    env_file:
     - .env
    depends_on:
      - smtp
    volumes:
      - "./data:/app/data"
      - "./frontend/dist:/app/frontend/dist"
    expose:
      - "3000"

  caddy:
    image: abiosoft/caddy:no-stats
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
    env_file:
      - .env
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./data/caddy:/root/.caddy"

