version: '3'
services:
  smtp:
    image: namshi/smtp
    env_file:
      - .env.dev

  server:
    build: .
    env_file:
      - .env.dev
    depends_on:
      - smtp
    volumes:
      - ".:/app"
    expose:
      - "3000"

  caddy:
    image: abiosoft/caddy:no-stats
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
    env_file:
      - .env.dev
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./data/caddy:/root/.caddy"

